### ISSUE TITLE
String "This device" is not translated

### ISSUE THREAD

**Issue by dmitriy-ilchenko** [csicar/Ning#26]
The string "This device" is hardcoded in code and is not present is strings.xml. Hence it cannot be translated.

**Comment by dmitriy-ilchenko** [comment]
In my opinion it is better to separate this device from other devices. Maybe it can be put at the top of the list.

**Comment by csicar** [comment]
Yeah. That is not a long-term solution. The data-model probably need to change as well:
`Model.kt Device` should probably get a `isScanningDevice` field, which can then be used for detecting the "own device"

Moving the scanning device to the top is not an optional solution IMO, because I am usually much more interested in information about the router (usually the first device) than the scanning device.
But I though maybe giving the "scanning device" a different background could be a good solution

**Comment by csicar** [comment]
I will probably not focus that issue right now, but I would be happy to take PRs for it :)
