### ISSUE TITLE
apk displays positive result for threat on virustotal.com (in 1 over 60 virus databases)

### ISSUE THREAD

**Issue by cainbantam** [csicar/Ning#56]
https://www.virustotal.com/gui/file/5945c3c64f27fc9beac74fdbe2ee0c1dc4011401ee72e8417251f4206d5c4ac1/detection

**Comment by csicar** [comment]
Not sure where that false positive is coming from..
I don't see any way to inspect why the AI of "Sangfor Engine Zero" classifies it as Malware, so I also see now way to fix it.

What APK did you upload? Is it a release from fdroid or a pre-release from Github?
If you have an idea for how to fix it, I'd be happy to try it out. Otherwise I would not waste time on making some AI happy about how the binary looks...

If you're concerned about the security of Ning, you can also check the code: It's only about 1.5k LOC in total

**Comment by cainbantam** [comment]
I downloaded it from fdroid. Ok, I didn't know it was an AI. Maybe you coud drop them a line to tell them to use your code to train their AI...
Thanks for the reply!

**Comment by csicar** [comment]
closing for now, as I can not see anything wrong with the source or pkgs generated.
